'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Upload,FileText,Target,CheckCircle2,ChevronRight,Mic,MicOff,Volume2,BarChart3,Sparkles,RefreshCw,ClipboardCheck,BrainCircuit} from 'lucide-react';

type Analysis={resumeScore:number;matchScore:number;optimizedMatchScore:number;strengths:string[];gaps:string[];recommendations:string[];dimensions:{name:string;score:number}[];optimizedBullets:string[];questions:{category:string;question:string;sampleAnswer:string}[]};
const demo:Analysis={resumeScore:82,matchScore:78,optimizedMatchScore:90,strengths:['本地生活/消费场景经验','KOL合作与活动运营','有明确GMV结果'],gaps:['目标行业经验较弱','商家拓展证据不足','广告投放深度不足'],recommendations:['用背景-动作-结果重写经历','只使用真实数据','补充JD中的真实关键词'],dimensions:[{name:'业务运营',score:90},{name:'数据分析',score:86},{name:'增长',score:88},{name:'KOL',score:84},{name:'广告投放',score:58},{name:'行业经验',score:42}],optimizedBullets:['基于订单数据与消费时段偏好，新增3款夜间团购套餐，三款套餐共同推动团购GMV提升30%。'],questions:[{category:'项目深挖',question:'你提到GMV提升30%，具体怎么算？',sampleAnswer:'我先看历史订单和项目销售表现，再按消费时段分析用户需求。发现夜间消费机会后新增3款套餐，其他团购整体基本稳定，因此重点复盘这次套餐调整带来的增量。'}]};
const steps=['简历录入','简历解析','简历诊断','目标岗位','JD解析','人岗匹配','针对性优化','优化后匹配度','面试问题','标准回答','模拟面试','面试评分','面试复盘','训练计划'];
export default function CareerPilot(){
 const [step,setStep]=useState(0),[resume,setResume]=useState(''),[jd,setJd]=useState(''),[filename,setFilename]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[loading,setLoading]=useState(false),[ans,setAns]=useState(''),[score,setScore]=useState<any>(null),[review,setReview]=useState<string[]>([]),[plan,setPlan]=useState<string[]>([]),[qIndex,setQIndex]=useState(0),[logs,setLogs]=useState<string[]>([]),[running,setRunning]=useState(false),[connected,setConnected]=useState(false);
 const pc=useRef<RTCPeerConnection|null>(null); const audio=useRef<HTMLAudioElement|null>(null);
 useEffect(()=>{try{const s=localStorage.getItem('careerpilot-v3');if(s){const x=JSON.parse(s);setResume(x.resume||'');setJd(x.jd||'');setFilename(x.filename||'');setAnalysis(x.analysis||null);setStep(x.step||0);setScore(x.score||null);setReview(x.review||[]);setPlan(x.plan||[]);}}catch{}},[]);
 useEffect(()=>{localStorage.setItem('careerpilot-v3',JSON.stringify({resume,jd,filename,analysis,step,score,review,plan}))},[resume,jd,filename,analysis,step,score,review,plan]);
 const questions=analysis?.questions||demo.questions; const currentQ=questions[Math.min(qIndex,questions.length-1)]||demo.questions[0];
 async function parseFile(file:File){setLoading(true);setFilename(file.name);try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/parse-file',{method:'POST',body:fd});const d=await r.json();if(d.text)setResume(d.text);else alert(d.error||'解析失败')}finally{setLoading(false)}}
 async function analyze(){if(!resume.trim()||!jd.trim()){alert('请先完成简历和目标JD输入');return}setLoading(true);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume,jd})});const d=await r.json();setAnalysis(d);setStep(2)}catch{setAnalysis(demo);setStep(2)}finally{setLoading(false)}}
 async function evaluate(){if(!ans.trim())return;setLoading(true);try{const r=await fetch('/api/interview/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:currentQ.question,answer:ans,resume,jd})});const d=await r.json();setScore(d);setStep(11)}finally{setLoading(false)}}
 async function nextQuestion(){if(!ans.trim())return;setLoading(true);try{const r=await fetch('/api/interview/next',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript:ans,resume,jd,history:questions.slice(0,qIndex+1)})});const d=await r.json();if(d.question){setAnalysis(a=>a?({...a,questions:[...a.questions,{category:'AI追问',question:d.question,sampleAnswer:''}]}):a);setQIndex(i=>i+1);setAns('');setLogs(x=>[...x,'AI追问：'+d.question])}}finally{setLoading(false)}}
 function finishReview(){const f=score?.feedback||['建议强化回答中的具体数据','明确个人动作与业务影响','结尾增加复盘与下一步'];setReview(f);setPlan(['用STAR结构重做高频项目题','针对JD缺口补充真实案例','完成1轮英文模拟面试并控制回答时长','下一轮重点练习数据与决策类追问']);setStep(13)}
 function speak(text:string){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';speechSynthesis.speak(u)}}
 async function startVoice(){setRunning(true);setLogs([]);try{const token=await fetch('/api/realtime/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instructions:`你是CareerPilot AI面试官。一次只问一个问题。候选人简历：${resume}\n目标JD：${jd}`})}).then(r=>r.json());if(token.demo){setLogs(['Demo模式：未配置 OPENAI_API_KEY，使用文字面试。']);speak(currentQ.question);return}if(!navigator.mediaDevices?.getUserMedia)throw new Error('浏览器不支持麦克风');const stream=await navigator.mediaDevices.getUserMedia({audio:true});const peer=new RTCPeerConnection();pc.current=peer;const remote=new Audio();remote.autoplay=true;audio.current=remote;peer.ontrack=e=>{remote.srcObject=e.streams[0]};stream.getTracks().forEach(t=>peer.addTrack(t,stream));const offer=await peer.createOffer();await peer.setLocalDescription(offer);const sdp=await fetch('https://api.openai.com/v1/realtime/calls?model='+encodeURIComponent(token.model||'gpt-realtime-2.1'),{method:'POST',headers:{Authorization:'Bearer '+token.client_secret,'Content-Type':'application/sdp'},body:offer.sdp});if(!sdp.ok)throw new Error(await sdp.text());await peer.setRemoteDescription({type:'answer',sdp:await sdp.text()});setConnected(true);setLogs(['实时语音已连接'])}catch(e:any){setLogs(['连接失败：'+e.message]);setRunning(false)}}
 function stopVoice(){pc.current?.getSenders().forEach(s=>s.track?.stop());pc.current?.close();pc.current=null;setRunning(false);setConnected(false);setLogs(x=>[...x,'面试已结束'])}
 function go(n:number){if(n<=step || (n===2&&analysis) || (n>=3&&analysis))setStep(n)}
 const progress=Math.round((step/(steps.length-1))*100);
 return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto max-w-7xl p-5 flex items-center justify-between"><div><b className="text-xl">CareerPilot AI V3</b><span className="ml-3 rounded-full bg-slate-100 px-3 py-1 text-xs">Career OS</span></div><button onClick={()=>{localStorage.removeItem('careerpilot-v3');location.reload()}} className="text-sm text-slate-500"><RefreshCw size={15} className="mr-1 inline"/>重新开始</button></div></header>
 <div className="mx-auto max-w-7xl p-6"><div className="mb-6 card p-4 overflow-x-auto"><div className="flex min-w-[1000px] items-center gap-1">{steps.map((s,i)=><button key={s} onClick={()=>go(i)} className={`flex items-center gap-1 whitespace-nowrap rounded-lg px-2 py-2 text-xs ${i===step?'bg-slate-900 text-white':i<step?'text-slate-700':'text-slate-400'}`}><span className="font-semibold">{i+1}</span>{s}{i<steps.length-1&&<ChevronRight size={12}/>}</button>)}</div><div className="mt-3 h-1 rounded bg-slate-100"><div className="h-1 rounded bg-slate-900" style={{width:`${progress}%`}}/></div></div>
 {step===0&&<Panel title="① 简历录入" icon={<Upload/>} desc="上传真实简历，CareerPilot 会先提取文本，再进入诊断。"><input type="file" accept=".pdf,.docx,.txt" onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])} className="block w-full rounded-xl border p-4"/><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="也可以直接粘贴简历内容" className="mt-4 h-64 w-full rounded-xl border p-4"/><div className="mt-4 flex items-center justify-between"><span className="text-sm text-slate-500">{filename||'尚未上传文件'} {loading&&'· 正在解析…'}</span><button className="btn-primary" onClick={()=>setStep(1)} disabled={!resume.trim()}>进入解析</button></div></Panel>}
 {step===1&&<Panel title="② 简历解析" icon={<FileText/>} desc="确认系统提取到的简历文本，然后进入诊断。"><div className="rounded-xl bg-slate-50 p-5 whitespace-pre-wrap max-h-[480px] overflow-auto text-sm leading-7">{resume}</div><div className="mt-5 flex justify-end"><button className="btn-primary" onClick={()=>setStep(2)}>开始诊断</button></div></Panel>}
 {step===2&&<Panel title="③ 简历诊断" icon={<ClipboardCheck/>} desc="先判断简历优势、问题和证据质量。"><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="先在这里粘贴目标岗位JD，下一步会进入JD解析" className="h-44 w-full rounded-xl border p-4"/><button className="btn-primary mt-4" onClick={analyze} disabled={loading}>{loading?'AI分析中…':'开始诊断与JD分析'}</button>{analysis&&<AnalysisCard a={analysis}/>}</Panel>}
 {step===3&&<Panel title="④ 输入目标岗位" icon={<Target/>} desc="输入你真正准备申请的目标岗位。"><textarea value={jd} onChange={e=>setJd(e.target.value)} className="h-72 w-full rounded-xl border p-4" placeholder="粘贴完整JD"/><button className="btn-primary mt-4" onClick={()=>setStep(4)} disabled={!jd.trim()}>解析JD</button></Panel>}
 {step===4&&<Panel title="⑤ JD解析器" icon={<BrainCircuit/>} desc="从JD中提取核心职责、能力和关键词。"><JDCard jd={jd}/><button className="btn-primary mt-5" onClick={()=>setStep(5)}>进入人岗匹配</button></Panel>}
 {step===5&&<Panel title="⑥ 人岗匹配分析" icon={<Target/>} desc="把简历证据和JD要求逐项对照。">{analysis?<MatchCard a={analysis}/>:<Empty/>}<button className="btn-primary mt-5" onClick={()=>setStep(6)}>生成针对性优化</button></Panel>}
 {step===6&&<Panel title="⑦ 简历针对性优化" icon={<Sparkles/>} desc="只使用简历已有事实，不虚构经历或数字.">{analysis?.optimizedBullets.map((x,i)=><div key={i} className="rounded-xl border p-4 mb-3">{x}</div>)}<div className="mt-5 flex justify-between"><span className="text-sm text-slate-500">建议：{analysis?.recommendations.join('；')}</span><button className="btn-primary" onClick={()=>setStep(7)}>查看优化后匹配度</button></div></Panel>}
 {step===7&&<Panel title="⑧ 优化后匹配度" icon={<BarChart3/>} desc="对比优化前后的岗位匹配结果。"><div className="grid md:grid-cols-3 gap-4"><Metric label="简历基础评分" value={analysis?.resumeScore}/><Metric label="优化前匹配度" value={analysis?.matchScore}/><Metric label="优化后匹配度" value={analysis?.optimizedMatchScore}/></div><button className="btn-primary mt-6" onClick={()=>setStep(8)}>预测面试问题</button></Panel>}
 {step===8&&<Panel title="⑨ 面试问题预测" icon={<BrainCircuit/>} desc="根据岗位缺口和简历证据生成高概率追问。">{questions.map((x,i)=><button key={i} onClick={()=>{setQIndex(i);setStep(9)}} className="w-full text-left rounded-xl border p-4 mb-3 hover:bg-slate-50"><span className="text-xs text-slate-500">{x.category}</span><div className="mt-1 font-medium">{x.question}</div></button>)}</Panel>}
 {step===9&&<Panel title="⑩ 标准回答生成" icon={<Sparkles/>} desc="先看结构，再进入模拟面试。"><div className="text-lg font-semibold">{currentQ.question}</div><div className="mt-4 rounded-xl bg-slate-50 p-5 leading-7">{currentQ.sampleAnswer||'请基于真实经历，用STAR结构组织回答：背景 → 任务 → 行动 → 结果 → 复盘。'}</div><button className="btn-primary mt-5" onClick={()=>setStep(10)}>开始模拟面试</button></Panel>}
 {step===10&&<Panel title="模拟面试" icon={<Mic/>} desc="支持文字模式，也保留V3实时语音面试能力。"><div className="rounded-xl border p-5"><div className="text-xs text-slate-500">{connected?'LIVE':'OFFLINE'}</div><h2 className="mt-2 text-xl font-bold">{currentQ.question}</h2><div className="my-8 flex justify-center"><button onClick={running?stopVoice:startVoice} className={`h-28 w-28 rounded-full text-white flex items-center justify-center ${running?'bg-red-600':'bg-slate-900'}`}>{running?<MicOff size={38}/>:<Mic size={38}/>}</button></div><div className="flex justify-center gap-3"><button onClick={()=>speak(currentQ.question)} className="btn-secondary"><Volume2 size={16} className="mr-2 inline"/>播放问题</button><button onClick={stopVoice} className="btn-secondary">结束</button></div>{logs.map((x,i)=><div key={i} className="mt-2 text-sm text-slate-500">{x}</div>)}</div><textarea value={ans} onChange={e=>setAns(e.target.value)} placeholder="文字模式：输入你的回答" className="mt-5 h-36 w-full rounded-xl border p-4"/><div className="mt-3 flex gap-3"><button className="btn-primary" onClick={evaluate} disabled={loading}>{loading?'评分中…':'提交并评分'}</button><button className="btn-secondary" onClick={nextQuestion}>让AI继续追问</button></div></Panel>}
 {step===11&&<Panel title="⑪ 面试评分" icon={<BarChart3/>} desc="从内容、逻辑、相关性、数据和表达五个维度反馈。"><div className="grid md:grid-cols-3 gap-4"><Metric label="综合评分" value={score?.score??78}/><Metric label="数据" value={score?.data??72}/><Metric label="逻辑" value={score?.logic??76}/></div><ul className="mt-6 space-y-3">{(score?.feedback||[]).map((x:string,i:number)=><li key={i} className="rounded-xl bg-slate-50 p-4">{x}</li>)}</ul><button className="btn-primary mt-5" onClick={finishReview}>进入面试复盘</button></Panel>}
 {step===12&&<Panel title="⑫ 面试复盘" icon={<ClipboardCheck/>} desc="把评分转化成下一轮训练动作。"><ul className="space-y-3">{review.map((x,i)=><li key={i} className="rounded-xl border p-4">{x}</li>)}</ul><button className="btn-primary mt-5" onClick={()=>setStep(13)}>生成下一轮训练计划</button></Panel>}
 {step===13&&<Panel title="下一轮训练计划" icon={<CheckCircle2/>} desc="训练计划来自本轮面试暴露出的能力缺口。"><div className="space-y-3">{plan.map((x,i)=><div key={i} className="rounded-xl border p-4 flex gap-3"><b>{i+1}</b><span>{x}</span></div>)}</div><button className="btn-secondary mt-5" onClick={()=>{setStep(8);setAns('');setScore(null)}}>开始下一轮训练</button></Panel>}
 </div></main>
}
function Panel(p:any){return <section className="card p-7"><div className="flex gap-3 items-start"><div className="rounded-xl bg-slate-100 p-3">{p.icon}</div><div><h1 className="text-2xl font-bold">{p.title}</h1><p className="mt-1 text-slate-500">{p.desc}</p></div></div><div className="mt-7">{p.children}</div></section>}
function Metric({label,value}:{label:string;value?:number}){return <div className="rounded-2xl border p-5"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-4xl font-bold">{value??'-'}<span className="text-lg">%</span></div></div>}
function AnalysisCard({a}:{a:Analysis}){return <div className="mt-6 grid md:grid-cols-2 gap-4"><div className="rounded-xl bg-slate-50 p-4"><b>优势</b><ul className="mt-2 space-y-1">{a.strengths.map(x=><li key={x}>• {x}</li>)}</ul></div><div className="rounded-xl bg-slate-50 p-4"><b>问题</b><ul className="mt-2 space-y-1">{a.gaps.map(x=><li key={x}>• {x}</li>)}</ul></div></div>}
function MatchCard({a}:{a:Analysis}){return <div className="grid md:grid-cols-2 gap-4">{a.dimensions.map(d=><div key={d.name} className="rounded-xl border p-4"><div className="flex justify-between"><span>{d.name}</span><b>{d.score}</b></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-slate-900" style={{width:`${d.score}%`}}/></div></div>)}</div>}
function JDCard({jd}:{jd:string}){const lines=jd.split(/[\n。；;]/).map(x=>x.trim()).filter(Boolean);return <div className="grid md:grid-cols-3 gap-4"><div className="rounded-xl bg-slate-50 p-4"><b>岗位职责</b><p className="mt-2 text-sm leading-6">{lines.slice(0,4).join('；')||'待提取'}</p></div><div className="rounded-xl bg-slate-50 p-4"><b>核心能力</b><p className="mt-2 text-sm leading-6">{lines.slice(4,8).join('；')||'从JD中继续识别'}</p></div><div className="rounded-xl bg-slate-50 p-4"><b>关键词</b><p className="mt-2 text-sm leading-6">{Array.from(new Set(lines.join(' ').split(/\s+/).filter(x=>x.length>2))).slice(0,12).join(' · ')||'待提取'}</p></div></div>}
function Empty(){return <div className="rounded-xl bg-slate-50 p-5">请先完成简历与JD分析。</div>}
